using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.Tilemaps;

//Debug file generated by AI to help with tilemap rendering issues. Attach this to any game object in the scene and set "dump" to true to print out information about all tilemap renderers in the scene and the main camera.
public class TilemapDebugDump : MonoBehaviour
{
    public bool dump = false;

    public void Update()
    {
        if (dump)
        {
            dump = false;
            DumpTilemaps();
        }
    }

    public void DumpTilemaps()
    {
        foreach (var tr in FindObjectsByType<TilemapRenderer>(FindObjectsSortMode.None))
        {
            Debug.Log(
                $"{tr.name} | " +
                $"mode={tr.mode} | " +
                $"sortingLayer={tr.sortingLayerName} | " +
                $"order={tr.sortingOrder} | " +
                $"material={(tr.sharedMaterial ? tr.sharedMaterial.name : "NULL")} | " +
                $"pos={tr.transform.position}"
            );
        }

        Camera cam = Camera.main;
        if (cam != null)
        {
            Debug.Log(
                $"CAMERA {cam.name} | " +
                $"pos={cam.transform.position} | " +
                $"rot={cam.transform.rotation.eulerAngles} | " +
                $"ortho={cam.orthographic} | " +
                $"size={cam.orthographicSize}"

            );
            Debug.Log("Camera transparency sort mode: " + Camera.main.transparencySortMode);
            Debug.Log("Camera transparency sort axis: " + Camera.main.transparencySortAxis);
        }
    }
}